# Workflow Name
name: Terraform CI

# Trigger the workflow
on:
  push:
    branches:
      - main
      - feature/**

jobs:
  terraform:
    name: Terraform Pipeline

    # GitHub Hosted Runner
    runs-on: ubuntu-latest

    steps:

      # Checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Install Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.2

      # Configure AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Debug - Shows current directory and files
      - name: Debug Repository
        run: |
          pwd
          ls -la
          echo "Terraform Files"
          find . -name "*.tf"
          echo "TFVARS Files"
          find . -name "*.tfvars"

      # Terraform Init
      - name: Terraform Init
        run: terraform init

      # Terraform Format Check
      - name: Terraform Format
        run: terraform fmt -check

      # Terraform Validate
      - name: Terraform Validate
        run: terraform validate

      # Terraform Plan
      - name: Terraform Plan
        run: terraform plan -var-file="terraform.tfvars"